name: Demo App Tests

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/
    strategy:
      matrix:
        dotnet: ["6.0.x"]
    name: Dotnet ${{ matrix.dotnet }} sample
    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - name: Execute dotnet
        run: dotnet build .

      - name: Test App Code
        run: dotnet test ./tests/demo.lib.tests/demo.lib.tests.csproj

      - name: Publish dotnet
        run: dotnet publish . -c Release

      # - name: Deploy to Server
      # - uses: actions/ssh-deploy@v4
      #   env:
      #     SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      #     REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
      #     REMOTE_USER: ${{ secrets.REMOTE_USER }}
      #     TARGET: ${{ secrets.REMOTE_TARGET }}
