name: Demo App Tests

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/
    strategy:
      matrix:
        dotnet: ["6.0.x"]
    name: Dotnet ${{ matrix.dotnet }} sample
    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - name: Execute dotnet
        run: dotnet build .

      - name: Test App Code
        run: dotnet test ./tests/demo.lib.tests/demo.lib.tests.csproj

      - name: Publish dotnet
        run: dotnet publish . -c Release

      # - name: Deploy to Server
      # - uses: actions/ssh-deploy@v4
      #   env:
      #     SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      #     REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
      #     REMOTE_USER: ${{ secrets.REMOTE_USER }}
      #     TARGET: ${{ secrets.REMOTE_TARGET }}
      #

      # - name: Upload Files
      #   uses: siva1024/scp-deployer@latest
      #   with:
      #     host: ${{ secrets.REMOTE_HOST }}
      #     username: ${{ secrets.REMOTE_USER }}
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     source: "./notes.txt"
      #     target: "~/"

      - name: ssh scp ssh pipelines
        uses: cross-the-world/ssh-scp-ssh-pipelines@v0.2.2
        env:
          WELCOME: "ssh scp ssh pipelines"
          LASTSSH: "Doing something after copying"
        with:
          host: ${{ secrets.REMOTE_HOST }}
          user: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          connect_timeout: 10s
          first_ssh: |
            echo $WELCOME 
            rm -f notes.txt
          scp: |
            './notes.txt*' => /home/deployer/
          last_ssh: |
            echo $LASTSSH
